### ISSUE TITLE
Wind direction change

### ISSUE THREAD

**Issue by pmoon00** [SkiFilmReviews/snow-forecast-sfr#28]
Hi there,

Would it be possible to get the wind direction added to this?  I've got the code change but I'm unsure of how to branch and create a pull request.  The code is below,

`windDirection: $(winds[i]).find('img').attr('alt').match(/[0-9]*\s([a-zA-Z]+)/)[1],`

The above line of code would become line 97, so would go below line 96 where it gets the wind value.

Thanks

**Comment by MikeSpitz** [comment]
Cheers for reaching out! I'll get this sorted with some tests in the new few days, will post here after it's been published. :+1:

**Comment by MikeSpitz** [comment]
Published on NPM, thanks again for the suggestion!
