### ISSUE TITLE
MaxTemp always null

### ISSUE THREAD

**Issue by alrocha** [SkiFilmReviews/snow-forecast-sfr#29]
Hi, I am using this great npm package but I might have found an issue, the maxTemp is always null, any idea? Thanks in advance

**Comment by alrocha** [comment]
Found the issue created a pr in case you'd like to update it :)

**Comment by MikeSpitz** [comment]
Merged in https://github.com/SkiFilmReviews/snow-forecast-sfr/pull/30

Thanks again for fixing!
